# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Melquisedec Portifolio
email: melqui.inbox@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Here you can find articles and tutorials about many things. In general I like
  write about technologies and computing stuff, things that I made on my spare
  time. From "how fix a shower" to "pattern recognition", the goal of this site
  is share and file my experiences to whom it may concern.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: melquiandrade1
github_username:  melqui-andrade

# Build settings
markdown: kramdown
